### ISSUE TITLE
script is failing to provide any output

### ISSUE THREAD

**Issue by secyodha** [NoDataFound/RiskIQ.SunBurst.Hunter#3]
script is failing with the below error after i provide the domain to scan (option 1) ... same result when i try other options as well.

Still Processing... Please hold

    NOTE: Full results have been saved to .output/domain.com/domain.com.json'

Traceback (most recent call last):
  File "RiskIQ.Sunburst.Hunter.py", line 366, in <module>
    menu()
  File "RiskIQ.Sunburst.Hunter.py", line 355, in menu
    sunburst_finder.sunburst_key()
  File "RiskIQ.Sunburst.Hunter.py", line 193, in sunburst_key
    for focus in response['results']:
KeyError: 'results'

**Comment by awslabspl** [comment]
@secyodha its **not** an error; as it begins with: `NOTE: ( ... )`

**Comment by secyodha** [comment]
sorry for the confusion.. you can ignore the first few lines ... error is captured further down ... KeyError: 'results'

**Comment by awslabspl** [comment]
> sorry for the confusion.. you can ignore the first few lines ... error is captured further down ... KeyError: 'results'
Thanks :) `KeyError` is still rather generic.
